#!/bin/bash

### Input image file paths
## count voxel in skeletons
# skeleton_mask_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/data/v1/stats/mean_FA_skeleton_mask.nii.gz"
# skeleton_mask_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/data/v2/stats/mean_FA_skeleton_mask.nii.gz"
# skeleton_mask_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/data/v3/stats/mean_FA_skeleton_mask.nii.gz"
# skeleton_mask_all="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/skeleton_mask_all.nii.gz"
## Count number of significant voxels per visit and DTI metric between cohorts
# AD_tstat1_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat1_v1_mask.nii.gz"
# AD_tstat1_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat1_v2_mask.nii.gz"
# AD_tstat1_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat1_v3_mask.nii.gz"
# AD_tstat1_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat1_overlap_mask.nii.gz"
# AD_tstat2_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat2_v1_mask.nii.gz"
# AD_tstat2_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat2_v2_mask.nii.gz"
# AD_tstat2_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat2_v3_mask.nii.gz"
# AD_tstat2_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/AD_tstat2_overlap_mask.nii.gz"
# FA_tstat1_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat1_v1_mask.nii.gz"
# FA_tstat1_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat1_v2_mask.nii.gz"
# FA_tstat1_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat1_v3_mask.nii.gz"
# FA_tstat1_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat1_overlap_mask.nii.gz"
# FA_tstat2_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat2_v1_mask.nii.gz"
# FA_tstat2_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat2_v2_mask.nii.gz"
# FA_tstat2_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat2_v3_mask.nii.gz"
# FA_tstat2_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/FA_tstat2_overlap_mask.nii.gz"
# MD_tstat1_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat1_v1_mask.nii.gz"
# MD_tstat1_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat1_v2_mask.nii.gz"
# MD_tstat1_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat1_v3_mask.nii.gz"
# MD_tstat1_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat1_overlap_mask.nii.gz"
# MD_tstat2_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat2_v1_mask.nii.gz"
# MD_tstat2_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat2_v2_mask.nii.gz"
# MD_tstat2_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat2_v3_mask.nii.gz"
# MD_tstat2_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/MD_tstat2_overlap_mask.nii.gz"
# RD_tstat1_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat1_v1_mask.nii.gz"
# RD_tstat1_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat1_v2_mask.nii.gz"
# RD_tstat1_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat1_v3_mask.nii.gz"
# RD_tstat1_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat1_overlap_mask.nii.gz"
# RD_tstat2_v1="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat2_v1_mask.nii.gz"
# RD_tstat2_v2="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat2_v2_mask.nii.gz"
# RD_tstat2_v3="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat2_v3_mask.nii.gz"
# RD_tstat2_overlap="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/mask/RD_tstat2_overlap_mask.nii.gz"
## Count number of significant voxels per DTI metric for the friedman test
FA_whole_skeleton_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_FA_friedman_clbp.nii.gz"
FA_whole_skeleton_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_FA_friedman_con.nii.gz"
FA_conjunction_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/FA_clust1_friedman_clbp_conjunction.nii.gz"
FA_conjunction_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/FA_clust1_friedman_con_conjunction.nii.gz"
MD_whole_skeleton_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_MD_friedman_clbp.nii.gz"
MD_whole_skeleton_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_MD_friedman_con.nii.gz"
MD_conjunction_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/MD_clust1_friedman_clbp_conjunction.nii.gz"
MD_conjunction_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/MD_clust1_friedman_con_conjunction.nii.gz"
RD_whole_skeleton_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_RD_friedman_clbp.nii.gz"
RD_whole_skeleton_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_RD_friedman_con.nii.gz"
RD_conjunction_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/RD_clust1_friedman_clbp_conjunction.nii.gz"
RD_conjunction_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/RD_clust1_friedman_con_conjunction.nii.gz"
AD_whole_skeleton_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_AD_friedman_clbp.nii.gz"
AD_whole_skeleton_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/whole_skeleton_AD_friedman_con.nii.gz"
AD_conjunction_clbp="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/AD_clust1_friedman_clbp_conjunction.nii.gz"
AD_conjunction_con="/Volumes/PT_DATA2/Marc-Antoine/myTBSS/friedman/results/AD_clust1_friedman_con_conjunction.nii.gz"

# Threshold value
threshold=6

# Threshold the images and count voxels
count_voxels() {
    local input_image="$1"
    local output_file="$2"
    
    fslmaths "$input_image" -thr $threshold -bin "$output_file"
    local num_voxels_thresh=$(fslstats "$output_file" -V | awk '{print $1}')
    local num_voxels=$(fslstats "$input_image" -V | awk '{print $1}')
    local ratio=$(echo "scale=4; $num_voxels_thresh / $num_voxels" | bc)
    echo "Number of voxels above threshold ($threshold) for $input_image: $num_voxels_thresh"
    echo "Ratio of significant voxels to total voxels for $input_image: $ratio"
}

### Display results 
## count voxel in skeletons
# count_voxels "$skeleton_mask_v1"
# count_voxels "$skeleton_mask_v2"
# count_voxels "$skeleton_mask_v3"
# count_voxels "$skeleton_mask_all"
## Count number of significant voxels per visit and DTI metric
# count_voxels "$AD_tstat1_v1"
# count_voxels "$AD_tstat1_v2"
# count_voxels "$AD_tstat1_v3"
# count_voxels "$AD_tstat1_overlap"
# count_voxels "$AD_tstat2_v1"
# count_voxels "$AD_tstat2_v2"
# count_voxels "$AD_tstat2_v3"
# count_voxels "$AD_tstat2_overlap"
# count_voxels "$FA_tstat1_v1"
# count_voxels "$FA_tstat1_v2"
# count_voxels "$FA_tstat1_v3"
# count_voxels "$FA_tstat1_overlap"
# count_voxels "$FA_tstat2_v1"
# count_voxels "$FA_tstat2_v2"
# count_voxels "$FA_tstat2_v3"
# count_voxels "$FA_tstat2_overlap"
# count_voxels "$MD_tstat1_v1"
# count_voxels "$MD_tstat1_v2"
# count_voxels "$MD_tstat1_v3"
# count_voxels "$MD_tstat1_overlap"
# count_voxels "$MD_tstat2_v1"
# count_voxels "$MD_tstat2_v2"
# count_voxels "$MD_tstat2_v3"
# count_voxels "$MD_tstat2_overlap"
# count_voxels "$RD_tstat1_v1"
# count_voxels "$RD_tstat1_v2"
# count_voxels "$RD_tstat1_v3"
# count_voxels "$RD_tstat1_overlap"
# count_voxels "$RD_tstat2_v1"
# count_voxels "$RD_tstat2_v2"
# count_voxels "$RD_tstat2_v3"
# count_voxels "$RD_tstat2_overlap"
## Count number of significant voxels per DTI metric for the friedman test
count_voxels "$FA_whole_skeleton_clbp"
count_voxels "$FA_whole_skeleton_con"
count_voxels "$FA_conjunction_clbp"
count_voxels "$FA_conjunction_con"
count_voxels "$MD_whole_skeleton_clbp"
count_voxels "$MD_whole_skeleton_con"
count_voxels "$MD_conjunction_clbp"
count_voxels "$MD_conjunction_con"
count_voxels "$RD_whole_skeleton_clbp"
count_voxels "$RD_whole_skeleton_con"
count_voxels "$RD_conjunction_clbp"
count_voxels "$RD_conjunction_con"
count_voxels "$AD_whole_skeleton_clbp"
count_voxels "$AD_whole_skeleton_con"
count_voxels "$AD_conjunction_clbp"
count_voxels "$AD_conjunction_con"